# -*- coding: utf-8 -*-
"""df_sustainability.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/10rY94jrB6apgptDQJg9gHjG0pGOAHsqf
"""

!pip install yfinance

import yfinance as yf
import pandas as pd

payload=pd.read_html('https://en.wikipedia.org/wiki/List_of_S%26P_500_companies')
first_table = payload[0]
second_table = payload[1]

sp500symbols=first_table['Symbol']

# Abfrage einer Aktie um die Spalten des Dataframes mit dessen ESG-Daten benennen zu können
tickers = yf.Ticker('msft')

esg_data = pd.DataFrame.transpose(tickers.sustainability)

for i in sp500symbols:
  aktien_daten=yf.Ticker(i)
  try:
    if aktien_daten.sustainability is not None:
      temp = pd.DataFrame.transpose(aktien_daten.sustainability)
      temp['company_ticker'] = str(aktien_daten.ticker)
      temp['beta']=aktien_daten.info['beta']
      temp['last_price']=aktien_daten.info['previousClose']
      temp['median_target']=aktien_daten.info['targetMeanPrice']
  
      print(str(aktien_daten.ticker))
      esg_data = esg_data.append(temp)
  except:
          pass

esg_data.to_pickle('esg')

